/* Sifarişlər, ölkə tarifləri və Excel ixracı */
const defaults={
  america:{name:'Amerika',currency:'$',rate:1.70,tariffs:[3.49,5.49,7.49,9.77]},
  turkey:{name:'Türkiyə',currency:'$',rate:1.70,tariffs:[1.49,2.49,3.49,4.29]},
  spain:{name:'İspaniya',currency:'€',rate:1.96,tariffs:[1.75,3.70,5.60,7.90]}
};
let state=window.__stockState||{active:null,orders:[],countries:defaults};
let pendingImage='',editing=null;
const $=id=>document.getElementById(id),money=n=>(Number(n)||0).toLocaleString('az-AZ',{minimumFractionDigits:2,maximumFractionDigits:2}),esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const save=()=>window.persistStockState(state);
const active=()=>state.orders.find(o=>o.id===state.active);
function country(k){return state.countries[k]||state.countries.america}
function shipping(g,k){g=+g||0;let a=country(k).tariffs;return!g?0:g<=100?a[0]:g<=250?a[1]:g<=500?a[2]:Math.ceil(g/1000)*a[3]}
function range(g){g=+g||0;return g<=100?'0–100 qr':g<=250?'101–250 qr':g<=500?'251–500 qr':g<=1000?'501 qr–1 kq':Math.ceil(g/1000)+' kq'}
function newOrder(){let o={id:Date.now().toString(),name:'Sifariş '+(state.orders.length+1),budget:0,createdAt:new Date().toISOString(),items:[]};state.orders.push(o);state.active=o.id;save();render()}
function calc(i){let c=country(i.country),q=+i.qty||0,ship=shipping(i.weight,i.country),purchase=((+i.price||0)*q+ship)*c.rate,sales=(+i.sale||0)*q;return{c,ship,purchase,sales,profit:sales-purchase,pct:sales?(sales-purchase)/sales:0}}
function totals(o){return o.items.reduce((a,i)=>{let x=calc(i);a.purchase+=x.purchase;a.items+=+i.qty||0;if(i.sold){a.sales+=x.sales;a.profit+=x.profit;a.sold+=+i.qty||0}return a},{purchase:0,sales:0,profit:0,items:0,sold:0})}
function allTotals(){return state.orders.reduce((a,o)=>{let t=totals(o);for(let k in a)a[k]+=t[k];return a},{purchase:0,sales:0,profit:0,items:0,sold:0})}
function dateTime(v){return new Intl.DateTimeFormat('az-AZ',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}
function compactImage(file){return new Promise((ok,no)=>{let r=new FileReader;r.onload=()=>{let im=new Image;im.onload=()=>{let c=document.createElement('canvas'),z=Math.min(1,180/Math.max(im.width,im.height));c.width=im.width*z;c.height=im.height*z;c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/png'))};im.src=r.result};r.onerror=no;r.readAsDataURL(file)})}
function tabs(){$('tabs').innerHTML=state.orders.map(o=>`<button class="tab ${o.id===state.active?'active':''}" data-id="${o.id}">${esc(o.name)}</button>`).join('')+'<button id="newOrder" class="plus">+</button>';document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.active=b.dataset.id;editing=null;save();render()});$('newOrder').onclick=newOrder}
function countryOptions(selected){return Object.entries(state.countries).map(([k,c])=>`<option value="${k}" ${k===selected?'selected':''}>${c.name}</option>`).join('')}
function render(){if(!state.orders.length)return newOrder();tabs();let o=active(),e=Number.isInteger(editing)?o.items[editing]:null;if(!e)editing=null;if(e)pendingImage=e.img||'';let t=totals(o),remain=(+o.budget||0)-t.purchase+t.sales;
  $('content').innerHTML=`<section class="box orderbar"><div class="field name"><label>Sifarişin adı</label><input id="orderName" value="${esc(o.name)}"></div><div class="field"><label>Yaradılma tarixi</label><input readonly value="${dateTime(o.createdAt)}"></div><div class="field"><label>Büdcə (₼)</label><input id="budget" type="number" min="0" value="${o.budget}"></div><div class="field"><label>Qeyd</label><input value="3 ölkə üzrə tarif" readonly></div><button id="deleteOrder" class="danger">Sifarişi sil</button></section>
  <section class="workspace"><aside class="box form"><h2>${e?'Məhsulu redaktə et':'Məhsul əlavə et'}</h2><div class="grid"><div class="field wide"><label>Məhsulun adı</label><input id="name" value="${e?esc(e.name):''}" placeholder="Məsələn: Kreatin"></div><div class="field"><label>Ölkə</label><select id="productCountry">${countryOptions(e?e.country:'america')}</select></div><div class="field"><label>Say</label><input id="qty" type="number" min="1" value="${e?e.qty:1}"></div><div class="field"><label>Alış qiyməti</label><input id="price" type="number" min="0" step=".01" value="${e?e.price:0}"></div><div class="field"><label>Satış qiyməti (₼)</label><input id="sale" type="number" min="0" step=".01" value="${e?e.sale:0}"></div><div class="field wide"><label>Çəki (qram, ümumi)</label><input id="weight" type="number" min="0" value="${e?e.weight:0}"></div><div class="field wide"><label>Məhsul şəkli</label><input id="image" class="file" type="file" accept="image/png,image/jpeg,image/webp">${e&&pendingImage?'<button id="deleteImage" class="remove" style="margin:8px 0 0">Şəkli sil</button>':''}</div></div><p class="hint">Seçilən ölkənin tarifi və məzənnəsi avtomatik tətbiq olunur.</p><button id="saveItem" class="primary save">${e?'Dəyişiklikləri yadda saxla':'Listə əlavə et'}</button>${e?'<button id="cancelEdit" class="secondary save">Ləğv et</button>':''}</aside>
  <section class="box tablebox"><div class="scroll"><table class="items"><thead><tr><th>Şəkil</th><th>Məhsul</th><th>Ölkə</th><th>Say</th><th>Alış</th><th>Karqo</th><th>Ümumi alış</th><th>Satış</th><th>Qazanc</th><th>Faiz</th><th>Status</th><th>Əməliyyat</th></tr></thead><tbody>${o.items.length?o.items.map((i,n)=>{let x=calc(i),im=i.img?`<img class="thumb" src="${i.img}">`:'<div class="noimg">Şəkil<br>yoxdur</div>';return`<tr><td>${im}</td><td><b>${esc(i.name)}</b></td><td>${x.c.name}</td><td class="num">${i.qty}</td><td class="num">${money((+i.price||0)*(+i.qty||0)*x.c.rate)} ₼</td><td class="num">${money(x.ship*x.c.rate)} ₼<br><small>${range(i.weight)}</small></td><td class="num">${money(x.purchase)} ₼</td><td class="num">${money(x.sales)} ₼</td><td class="num lime">${money(x.profit)} ₼</td><td class="num">${(x.pct*100).toFixed(1)}%</td><td><button class="sold" data-sold="${n}">${i.sold?'Satılıb':'Satıldı et'}</button></td><td><button class="edit" data-edit="${n}">Redaktə</button><button class="remove" data-remove="${n}">Sil</button></td></tr>`}).join(''):'<tr><td colspan="12" class="empty">Hələ məhsul əlavə edilməyib.<br><small>Soldakı formdan ilk məhsulunu əlavə et.</small></td></tr>'}</tbody></table></div></section></section>
  <section class="metrics"><div class="box metric"><span>Ümumi alış</span><strong>${money(t.purchase)} ₼</strong></div><div class="box metric"><span>Satışdan daxil olan</span><strong>${money(t.sales)} ₼</strong></div><div class="box metric"><span>Satış qazancı</span><strong class="lime">${money(t.profit)} ₼</strong></div><div class="box metric"><span>Büdcədə qalan</span><strong class="lime">${money(remain)} ₼</strong></div></section><section class="box tariff-box"><h2>Aktiv karqo tarifləri</h2><div class="tariff-list">${Object.values(state.countries).map(c=>`<div><b>${c.name}</b>0–100 qr: ${c.tariffs[0]} ${c.currency}<br>501 qr–1 kq: ${c.tariffs[3]} ${c.currency}</div>`).join('')}</div></section>`;
  bind(o,e);
}
function bind(o,e){
 $('orderName').oninput=v=>{o.name=v.target.value||'Adsız sifariş';save();tabs()};$('budget').oninput=v=>{o.budget=+v.target.value||0;save();render()};$('deleteOrder').onclick=()=>{if(confirm('Sifariş silinsin?')){state.orders=state.orders.filter(x=>x.id!==o.id);state.active=state.orders[0]?.id||null;save();render()}};
 $('image').onchange=async e=>{if(e.target.files[0])pendingImage=await compactImage(e.target.files[0])};if($('deleteImage'))$('deleteImage').onclick=()=>{pendingImage='';render()};if($('cancelEdit'))$('cancelEdit').onclick=()=>{editing=null;pendingImage='';render()};
 $('saveItem').onclick=()=>{let i={name:$('name').value.trim(),country:$('productCountry').value,qty:+$('qty').value||0,price:+$('price').value||0,sale:+$('sale').value||0,weight:+$('weight').value||0,img:pendingImage,sold:e?e.sold:false};if(!i.name||!i.qty)return alert('Məhsulun adını və sayını yazın.');if(e)o.items[editing]=i;else o.items.push(i);editing=null;pendingImage='';save();render()};
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=+b.dataset.edit;render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{o.items.splice(+b.dataset.remove,1);save();render()});document.querySelectorAll('[data-sold]').forEach(b=>b.onclick=()=>{let item=o.items[+b.dataset.sold];item.sold=!item.sold;item.soldAt=item.sold?new Date().toISOString():null;save();render()});
}
function showModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}function hideModal(){$('modal').classList.add('hidden')}
function tariffSettings(){let rows=Object.entries(state.countries).map(([k,c])=>`<div class="country-editor"><b>${c.name} (${c.currency})</b>${c.tariffs.map((v,n)=>`<input data-country="${k}" data-tariff="${n}" type="number" step=".01" value="${v}">`).join('')}<input data-rate="${k}" type="number" step=".01" value="${c.rate}" title="AZN məzənnəsi"></div>`).join('');showModal('Tarif və məzənnə ayarları',`<p class="hint">Sıra: 0–100 qr, 101–250 qr, 251–500 qr, 501 qr–1 kq, AZN məzənnəsi.</p>${rows}<button id="saveTariffs" class="primary" style="margin-top:12px">Tarifləri yadda saxla</button>`);$('saveTariffs').onclick=()=>{document.querySelectorAll('[data-tariff]').forEach(x=>state.countries[x.dataset.country].tariffs[+x.dataset.tariff]=+x.value||0);document.querySelectorAll('[data-rate]').forEach(x=>state.countries[x.dataset.rate].rate=+x.value||0);save();hideModal();render()}}
function exportExcel(){if(!window.XLSX)return alert('Excel modulu yüklənmədi.');let wb=XLSX.utils.book_new();state.orders.forEach((o,n)=>{let rows=[['Məhsul','Ölkə','Say','Alış (₼)','Karqo (₼)','Ümumi alış','Satış','Qazanc','Faiz','Status']];o.items.forEach(i=>{let x=calc(i);rows.push([i.name,x.c.name,i.qty,(+i.price||0)*(+i.qty||0)*x.c.rate,x.ship*x.c.rate,x.purchase,x.sales,x.profit,x.pct,i.sold?'Satılıb':'Satılmayıb'])});let ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:30},{wch:13},{wch:8},{wch:15},{wch:15},{wch:17},{wch:15},{wch:15},{wch:11},{wch:14}];XLSX.utils.book_append_sheet(wb,ws,(o.name||'Sifariş '+(n+1)).slice(0,31))});XLSX.writeFile(wb,'stockpilot-hesabat.xlsx')}
window.startStockPilot=()=>{$('profileBtn').onclick=()=>location.href='account.html';$('openStats').onclick=()=>location.href='account.html';$('openSettings').onclick=tariffSettings;$('newOrderTop').onclick=newOrder;$('exportBtn').onclick=exportExcel;$('closeModal').onclick=hideModal;$('modal').onclick=e=>{if(e.target===$('modal'))hideModal()};render()};
