const shop = new URLSearchParams(location.search).get('shop');
let products = [], cart = [], category = 'Hamısı';
const $ = (id) => document.getElementById(id);
const money = (n) => `${(Number(n)||0).toLocaleString('az-AZ',{minimumFractionDigits:2,maximumFractionDigits:2})} ₼`;
const esc = (s) => String(s||'').replace(/[&<>"']/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function render(){ const cats=['Hamısı',...new Set(products.map(p=>p.category))]; $('categories').innerHTML=cats.map(c=>`<button class="${c===category?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join(''); $('products').innerHTML=products.filter(p=>category==='Hamısı'||p.category===category).map(p=>`<article class="product">${p.image?`<img src="${p.image}">`:'<div class="placeholder">Şəkil yoxdur</div>'}<small>${esc(p.category)}</small><h2>${esc(p.name)}</h2><footer><span class="price">${money(p.price)}</span><button data-add="${p.id}">Səbətə</button></footer></article>`).join('')||'<p>Məhsul hazırda yoxdur.</p>'; document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.add),line=cart.find(x=>x.id===p.id);if(line){if(line.quantity<line.maxQuantity)line.quantity++}else cart.push({...p,maxQuantity:p.quantity,quantity:1});renderCart()}); }
function renderCart(){ $('cartCount').textContent=cart.reduce((s,x)=>s+x.quantity,0);$('cartLines').innerHTML=cart.map(x=>`<div class="line"><span><b>${esc(x.name)}</b><small>${money(x.price)} × ${x.quantity}</small></span><span><button data-minus="${x.id}">−</button><button data-plus="${x.id}">+</button></span></div>`).join('')||'<p>Səbət boşdur.</p>';document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.minus);x.quantity--;if(!x.quantity)cart=cart.filter(i=>i!==x);renderCart()});document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.plus);if(x.quantity<x.maxQuantity) x.quantity++;renderCart()}); }
async function boot(){ if(!shop){$('shopName').textContent='Mağaza linki düzgün deyil';return}const r=await fetch(`/api/store/${encodeURIComponent(shop)}`);if(!r.ok){$('shopName').textContent='Mağaza tapılmadı';return}const data=await r.json();products=data.products||[];$('shopName').textContent=`${data.shop.name} mağazası`;$('shopTag').textContent='STOCKPILOT MAĞAZA';render();renderCart() }
$('cartButton').onclick=()=>$('cart').classList.remove('hidden');$('closeCart').onclick=()=>$('cart').classList.add('hidden');$('checkout').onsubmit=async(e)=>{e.preventDefault();if(!cart.length)return $('message').textContent='Səbət boşdur.';const body=Object.fromEntries(new FormData(e.target));body.cart=cart.map(({id,quantity})=>({id,quantity}));const r=await fetch(`/api/store/${encodeURIComponent(shop)}/orders`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return $('message').textContent=d.error||'Xəta oldu.';$('message').textContent='Sifarişiniz qəbul edildi. Tezliklə əlaqə saxlanılacaq.';cart=[];renderCart();e.target.reset()};boot();
